demo: srv cli trans

srv: netJumperSrv.cc
	g++ netJumperSrv.cc -o srv

cli: netJumperCli.cc
	g++ netJumperCli.cc -o cli

trans: netJumperTrans.cc
	g++ netJumperTrans.cc -o trans

clean:
	rm -f srv cli trans
